swagger: "2.0"
info:
  description: Logger processor for MQTT
  version: "1.0.0"
  title: MQTT Logger Processor
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /

paths:
  /push/queue:
    post:
      operationId: "api.controller.queue.push_to_task_queue"
      responses:
        200:
          description: "push to task queue"


  /pull/log:
    post:
      operationId: "api.controller.logger.pull_log_data"
      responses:
        200:
          description: "pull log data"
